import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";
import { OrderProvider } from "@/context/OrderContext";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bandage Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/vid.png" sizes="any" />
      </head>
      <body
        className={`${font.className} antialiased`}
        style={{
          display: "flex",
          flexDirection: "column",
          width: "100%",
          overflowX: "hidden",
        }}
      >

        {/* Main Content */}
        <div
          className="flex-1 w-full max-w-[1440px] mx-auto overflow-x-hidden"
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "flex-start",
            width: "100%",
          }}
        > <Toaster position="top-center" />
        
        <OrderProvider>
          <CartProvider>
          {children}
          </CartProvider>
        </OrderProvider>
        </div>
      </body>
    </html>
  );
}
